# -*- coding: utf-8 -*-
"""decision tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTXRgZJIxHdqKuUQompaFAL2SbXjGCWt
"""

import sklearn.datasets as datas
irisdata = datas.load_iris()
irisdata

import pandas as pd
import sklearn.datasets as datas
from sklearn import tree
from sklearn.model_selection import train_test_split

irisdata.keys()

import pandas as pd
import sklearn.datasets as datas
from sklearn import tree
from sklearn.model_selection import train_test_split

irisdata.keys()

irisdata.target

irisdata.target_names

irisIrisData=pd.DataFrame(irisdata.data)
irisIrisData.head(5)

irisdata.feature_names

irisIndTrain, irisIndTest, irisDepTrain, irisDepTest = train_test_split(
    irisIrisData,
    irisdata.target,
    test_size=0.2,
    random_state=0
)





