# -*- coding: utf-8 -*-
"""EDA.jpynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176iqg-5gZO2qu4RWosEJRMyrthozsx4k
"""

# IRIS DATASET - BASICS, COUNTS, DESCRIPTIVES,GROUPS,
# FEATURE ENGINEERING AND EDA
# ================================================================

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# 1.Load the iris dataset
# -----------------------------------------------------------------
df = sns.load_dataset("iris")

print(df.tail(10))

print(df.tail(5))

# Display Column Names
print("Columns:",df.columns.tolist())

print(df.dtypes)

print(df.info)

df.info()

print(df.isnull().sum())



#check total nummber of missing values
print("Total missing values:",df.isnull().sum().sum())

#count observation of each species
print(df["species"].value_counts(normalize=True)*100)

#count unique values in species
print("Number of unique species:", df["species"].nunique())

#count unique values in species
print("Number of unique species:", df["species"].unique())

"""### 1. Summary Statistics
Generating descriptive statistics like mean, standard deviation, and quartiles.
"""

display(df.describe())

"""### 2. Grouped Aggregations
Calculating the mean and standard deviation for each feature, grouped by species.
"""

display(df.groupby('species').agg(['mean', 'std']))

"""### 3. Sorting and Filtering
Sorting the data by petal length and filtering for large flowers.
"""

# Sort by petal length descending
display(df.sort_values(by='petal_length', ascending=False).head())

# Filter for rows where petal_width is greater than 2.0
large_petals = df[df['petal_width'] > 2.0]
print(f"Samples with petal_width > 2.0: {len(large_petals)}")

"""### 4. Correlation Matrix
Checking how numerical features correlate with one another.
"""

display(df.corr(numeric_only=True))

"""### 5. Feature Engineering
Creating a new feature 'sepal_area' as a product of length and width.
"""

df['sepal_area'] = df['sepal_length'] * df['sepal_width']
display(df.head())

"""### 6. Data Visualization
Using a pairplot to see relationships between all features, colored by species.
"""

sns.pairplot(df, hue='species')
plt.show()

"""### 7. Distribution Analysis
Using boxplots to visualize the distribution of Petal Length for each species.
"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='species', y='petal_length', data=df)
plt.title('Distribution of Petal Length by Species')
plt.show()

"""### 8. Violin Plots
Violin plots combine box plots and density plots to show the full distribution of the data.
"""

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
sns.violinplot(x='species', y='sepal_length', data=df)
plt.subplot(1, 2, 2)
sns.violinplot(x='species', y='sepal_width', data=df)
plt.tight_layout()
plt.show()

"""### 9. Engineered Feature Analysis
Visualizing the relationship between Petal Length and the engineered 'Sepal Area'.
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(x='sepal_area', y='petal_length', hue='species', data=df, s=100)
plt.title('Sepal Area vs Petal Length')
plt.grid(True)
plt.show()



"""### Selecting Numerical Columns
Using `select_dtypes` to filter for only columns containing numeric data types (integers and floats).
"""

numeric_df = df.select_dtypes(include=[np.number])
display(numeric_df.head())

print(df.select_dtypes("number").mean())

"""### 10. Average Metrics by Species (Bar Chart)
Visualizing the mean values of numerical features for each species to compare their physical characteristics.
"""

df_mean = df.groupby('species').mean(numeric_only=True).reset_index()
# Reshaping for easier plotting with Seaborn
df_melted = df_mean.melt(id_vars='species', var_name='Metric', value_name='Average Value')

plt.figure(figsize=(12, 6))
sns.barplot(data=df_melted, x='Metric', y='Average Value', hue='species')
plt.title('Average Measurements by Iris Species')
plt.ylabel('Value (cm / area)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

sns.countplot(data=df, x="species")
plt.title("Number of Flowers by species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()

"""### 11. Maximum Measurements by Flower Name (Species)
This chart identifies the largest recorded values for each metric across the three iris species.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate max values per species
df_max = df.groupby('species').max(numeric_only=True).reset_index()

# Reshape for bar chart
df_max_melted = df_max.melt(id_vars='species', var_name='Feature', value_name='Max Value')

# Plotting
plt.figure(figsize=(12, 6))
sns.barplot(data=df_max_melted, x='Feature', y='Max Value', hue='species', palette='muted')
plt.title('Maximum Recorded Measurements by Flower Species')
plt.ylabel('Value (cm / area)')
plt.legend(title='Flower Name')
plt.show()

"""### 12. Minimum Measurements by Species
This identifies the smallest recorded values for each metric.
"""

# Calculate min values per species
df_min = df.groupby('species').min(numeric_only=True).reset_index()
df_min_melted = df_min.melt(id_vars='species', var_name='Feature', value_name='Min Value')

plt.figure(figsize=(12, 6))
sns.barplot(data=df_min_melted, x='Feature', y='Min Value', hue='species', palette='pastel')
plt.title('Minimum Recorded Measurements by Flower Species')
plt.ylabel('Value (cm / area)')
plt.show()

"""### 13. Horizontal Analysis: Average Sepal Area
A focused look at the engineered feature 'Sepal Area'.
"""

plt.figure(figsize=(8, 4))
sns.barplot(data=df, x='sepal_area', y='species', estimator=np.mean, errorbar=None, palette='viridis')
plt.title('Average Sepal Area by Species')
plt.xlabel('Mean Sepal Area')
plt.ylabel('Flower Name')
plt.show()

"""### 14. Renaming Columns
Changing column names to be more descriptive or formal.
"""

# Create a copy and rename columns
df_renamed = df.rename(columns={
    'sepal_length': 'Sepal_Length_CM',
    'sepal_width': 'Sepal_Width_CM',
    'petal_length': 'Petal_Length_CM',
    'petal_width': 'Petal_Width_CM'
})
display(df_renamed.head())

"""### 15. Identifying Outliers (IQR Method)
Mathematically finding rows where the Petal Length is unusually high or low.
"""

Q1 = df['petal_length'].quantile(0.25)
Q3 = df['petal_length'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['petal_length'] < lower_bound) | (df['petal_length'] > upper_bound)]
print(f"Number of Petal Length outliers: {len(outliers)}")
display(outliers)

"""### 16. Pivot Tables
Creating a summary table of petal lengths across species.
"""

# Using pivot_table to see the average petal length per species
pivot_view = df.pivot_table(index='species', values='petal_length', aggfunc='mean')
display(pivot_view)

"""### 17. Custom Aggregation (Data Range)
Calculating the difference between maximum and minimum values for each measurement per species.
"""

# Define a custom function to calculate the range
def get_range(x):
    return x.max() - x.min()

range_analysis = df.groupby('species').agg(get_range)
display(range_analysis)

"""### 18. Mapping Categorical Values
Creating a numeric encoding for the 'species' column using a dictionary map.
"""

species_map = {'setosa': 0, 'versicolor': 1, 'virginica': 2}
df['species_code'] = df['species'].map(species_map)
display(df[['species', 'species_code']].drop_duplicates())

"""### 19. Applying Lambda Functions
Categorizing flowers into 'Small' or 'Large' based on Petal Length.
"""

# Labeling rows based on petal length threshold
df['size_label'] = df['petal_length'].apply(lambda x: 'Large' if x > 4 else 'Small')
display(df[['petal_length', 'size_label', 'species']].sample(10))

"""### 20. Essential Quick Commands
These simple commands are used in almost every data analysis project to understand the structure and size of the data.
"""

# Check the dimensions (rows, columns)
print(f"Dataset Shape: {df.shape}")

# Get a random sample of 3 rows
print("\nRandom Sample:")
display(df.sample(3))

# Count unique values across all columns
print("\nUnique values per column:")
print(df.nunique())

# Check memory usage of each column in bytes
print("\nMemory Usage (bytes):")
print(df.memory_usage(deep=True))

"""### 21. Checking for Duplicates
Identifying if there are any redundant rows in the dataset.
"""

# Count total duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

# Show the duplicate rows if they exist
if duplicate_count > 0:
    display(df[df.duplicated(keep=False)])

"""### 22. Finding the Location of Extremes
Using `idxmax` and `idxmin` to find the specific rows with the largest/smallest values.
"""

# Find the index of the flower with the longest petal
max_petal_idx = df['petal_length'].idxmax()
min_petal_idx = df['petal_length'].idxmin()

print(f"Row with longest petal (Index {max_petal_idx}):")
display(df.loc[[max_petal_idx]])

print(f"\nRow with shortest petal (Index {min_petal_idx}):")
display(df.loc[[min_petal_idx]])

"""### 23. Simple Column Correlation
Checking the relationship between two specific features.
"""

correlation = df['petal_length'].corr(df['petal_width'])
print(f"Correlation between Petal Length and Petal Width: {correlation:.4f}")

sns.histplot(
    data=df,
    x="sepal_length",
    bins=10,
    kde=True
)

sns.histplot(
    data=df,
    x="petal_length",
    bins=10,
    kde=True
)

sns.histplot(
    data=df,
    x="petal_width",
    bins=10,
    kde=True
)



sns.histplot(
    data=df,
    x="petal_length",
    bins=50,
    kde=True
)

plt.figure(figsize=(10, 6))
sns.boxplot(x='species', y='petal_length', data=df)
plt.title('Distribution of Petal Length by Species')
plt.show()

