# -*- coding: utf-8 -*-
"""Linear Regression on Bostonhousing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPCqO_sxdPbetdYJ6BkBxhIlc4PgWoyF
"""

# ===============================
# 1. IMPORT LIBRARIES
# ===============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error,
r2_score

import statsmodels.formula.api as smf

# 2. LOAD DATA
# ===============================
url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
df = pd.read_csv(url)

df.head()

df.describe()

# 3. EDA
# ===============================
# Histogram
df.hist(figsize=(12,10))
plt.suptitle("Feature Distributions")
plt.show()

# Scatter plot (SLR relationship)
plt.scatter(df['rm'], df['medv'])
plt.xlabel("Average Rooms (RM)")
plt.ylabel("House Price (MEDV)")
plt.title("SLR: RM vs MEDV")
plt.show()

# Scatter plot (SLR relationship)
plt.scatter(df['lstat'], df['medv'])
plt.xlabel("Lower status (Lstat)")
plt.ylabel("House Price (MEDV)")
plt.title("SLR: Lstat vs MEDV")
plt.show()

# Boxplot (outliers)
plt.boxplot(df['medv'])
plt.title("Boxplot of House Prices")
plt.show()

# 4. HEATMAP (CORRELATION)
# ===============================
plt.figure(figsize=(10,8))
corr = df.corr()

sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# 5. SIMPLE LINEAR REGRESSION (SLR)
# ===============================
X_slr = df[['rm']]
y = df['medv']

X_train, X_test, y_train, y_test = train_test_split(X_slr, y, test_size=0.3, random_state=565)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

slr = LinearRegression()
slr.fit(X_train, y_train)

y_pred_slr = slr.predict(X_test)
y_pred_slr

print("\nSLR Results")
print("\nSLR Results")
print("R2:", r2_score(y_test, y_pred_slr))

# Regression line visualization
plt.scatter(X_test, y_test, label="Actual")
plt.plot(X_test, y_pred_slr, color='red', label="Predicted Line")
plt.title("SLR Fit: RM vs MEDV")
plt.legend()
plt.show()

"""# Multiple Linear Regression Model"""

# 6. MULTIPLE LINEAR REGRESSION (MLR)
# ===============================
X_mlr = df[['rm', 'lstat', 'ptratio']]

X_train, X_test, y_train, y_test = train_test_split(X_mlr, y, test_size=0.3, random_state=42)

mlr = LinearRegression()
mlr.fit(X_train, y_train)
y_pred_mlr = mlr.predict(X_test)
y_pred_mlr

print("\nMLR Results")
print("R2:", r2_score(y_test, y_pred_mlr))

# Coefficients
coef_df = pd.DataFrame({
    "Feature": X_mlr.columns,
    "Coefficient": mlr.coef_
})
print(coef_df)

# 7. PREDICTIONS TABLE
# ===============================
pred_df = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred_mlr
})

pred_df.head()

"""# Method II"""



