# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tiz128TAnWou-iaHNyPLBqs71Q_uQIct
"""

# Commented out IPython magic to ensure Python compatibility.
#Import Packages
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import metrics #metrics for diagnostics
from sklearn.metrics import roc_curve,auc,recall_score,precision_score,accuracy_score,f1_score
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
# %matplotlib inline

#Print multiple statement in the same line
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

##Import file
df=pd.read_csv('/content/archive.zip')
df.head()

#Explore data
df.shape
type(df)
df.size
df.head()
df.tail()

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set(style="whitegrid")

# Convert TotalCharges to numeric and handle missing values
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'].fillna(df['TotalCharges'].mean(), inplace=True)

# 1. Basic EDA
print(df.info())
print(df.describe(include="all"))
print(df['Churn'].value_counts(normalize=True) * 100)

# 2. Histogram for numeric variables

numeric_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
df[numeric_cols].hist(figsize=(12,6), bins=30, edgecolor='black')
plt.suptitle("Histograms of Numeric Variables")
plt.show()

# 3. Bar plot for categorical variables
categorical_cols = ['gender', 'SeniorCitizen', 'Partner', 'Dependents',
                    'PhoneService', 'MultipleLines', 'InternetService',
                    'Contract', 'PaperlessBilling', 'PaymentMethod']

for col in categorical_cols:
    plt.figure(figsize=(6,4))
    sns.countplot(x=col, data=df, hue="Churn")
    plt.title(f"{col} vs Churn")
    plt.xticks(rotation=45)
    plt.show()

# 4. Stacked bar chart (Bivariate analysis: IV vs Churn)
for col in categorical_cols:
    cross_tab = pd.crosstab(df[col], df['Churn'], normalize='index') * 100
    cross_tab.plot(kind='bar', stacked=True, figsize=(7,4), colormap="coolwarm")
    plt.title(f"Stacked Bar Chart of {col} vs Churn (%)")
    plt.ylabel("Percentage")
    plt.show()

# 5. Correlation heatmap for numeric variables
plt.figure(figsize=(8,6))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap="Blues", fmt=".2f")
plt.title("Correlation Heatmap of Numeric Variables")
plt.show()

#Checking for missing values
pd.isnull(df).any()

#Find out variable type. Note that object means string or categorical in the below output
df.info()

#Except the below variables all are categorical
df.describe()

#Convert Total charges into numeric, coercing errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
#Missing value imputation
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].mean())

#Convert Total charges into numeric
df['TotalCharges']=pd.to_numeric(df.TotalCharges, errors='coerce')
df.head()

#frequency of a categorical variable
print('count of Labels')
df.groupby("Churn").size()

1869/(1869+5174)

#Convert churn from (yes,No) to (0,1)
le=preprocessing.LabelEncoder()
le.fit(df['Churn'])
list(le.classes_)

dfn=le.transform(df['Churn'])
le.inverse_transform([0,1])
df['y']=dfn
df.info()
df.columns

#Separate out independent categorical variables for conversion into numerical
x_catg=df.loc[:,('gender','Partner', 'Dependents','PhoneService', 'MultipleLines',
                 'InternetService',    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling','PaymentMethod')]

#Display top 5 rows
x_catg.head()
#Display shape
x_catg.shape

#Separate out independent numerical variables
x_num=df.loc[:,('SeniorCitizen','tenure','MonthlyCharges','TotalCharges')]
x_num

# Convert categorical variables into dummy coding
x_num1=pd.get_dummies(x_catg)
x_num1.head()

#get all x's together
x=pd.concat([x_num1,x_num],axis=1)
x.head()

x.head()

# Create dep variable
y=df['y']
y.head()

#create training and test
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.25,random_state=1)
train_x.shape
train_y.shape
test_x.shape
test_y.shape

train_x.isnull().sum()

#Logistic Regression model
from sklearn.linear_model import LogisticRegression
log=LogisticRegression(max_iter=50000)

train_x.isnull().sum()

#Fit a model
log.fit(train_x,train_y)

#
log.coef_

#Find out the key predictor of churn
coeff=pd.concat([pd.DataFrame(x.columns),pd.DataFrame(np.transpose(log.coef_))],axis=1)
coeff.columns=("Variable","Coeff")
coeff.sort_values=("variable","ascending=True")

#Generate Model Diagnostics
classes=log.predict(test_x)
classes

print(classes.size)

print('Positive cases in Test data:', test_y[test_y == 1].shape[0])

print('Negative cases in Test data:', test_y[test_y == 0].shape[0])

#Generate Model Diagnostics
classes=log.predict(test_x)
print(classes.size)
print('Positive cases in Test data:', test_y[test_y == 1].shape[0])
print('Negative cases in Test data:', test_y[test_y == 0].shape[0])
#Precision and Recall
print('Accuracy Score')
print(metrics.accuracy_score(test_y,classes))
print('Precision/Recall Metrics')
print(metrics.classification_report(test_y,classes))
print('AUC')
auc=metrics.roc_auc_score(test_y,classes)
auc

print('Confusion Matrix')
cf=metrics.confusion_matrix(test_y,classes)
lbl1=["Predicted 0","Predicted 1"]
lbl2=["True 0","True 1"]
sns.heatmap(cf,annot=True,cmap="Greens",fmt="d",xticklabels=lbl1,yticklabels=lbl2)
plt.show();

(1189+241)/(1189+139+193+241)

#ROC Chart
fpr,tpr,th=roc_curve(test_y,classes)
roc_auc=metrics.auc(fpr,tpr)
import matplotlib.pyplot as plt
plt.title('ROCR CHART')
plt.plot(fpr,tpr,'b', label='AUC= %0.2f'% roc_auc)
plt.legend(loc='lower right')
plt.plot([0,1],[0,1],'o--')
plt.xlim([0,1])
plt.ylim([0,1])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show();
#

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

# 1. Decision Tree
dtree = DecisionTreeClassifier(max_depth=3, random_state=42)
dtree.fit(train_x, train_y)

# 2. Support Vector Machine
svm = SVC(kernel='linear', probability=True, random_state=42)
svm.fit(train_x, train_y)

# 3. Neural Network (simple MLP)
nn = MLPClassifier(hidden_layer_sizes=(32,16), activation='relu',
                   solver='adam', max_iter=500, random_state=42)
nn.fit(train_x, train_y)

# 4. AdaBoost
ada = AdaBoostClassifier(n_estimators=3, random_state=42)
ada.fit(train_x, train_y)

# 5. Random Forest
rf = RandomForestClassifier(n_estimators=3, max_depth=2, random_state=42)
rf.fit(train_x, train_y)

from sklearn.metrics import classification_report, accuracy_score

models = {'Decision Tree': dtree,
          'SVM': svm,
          'Neural Net': nn,
          'AdaBoost': ada,
          'Random Forest': rf}

for name, model in models.items():
    preds = model.predict(test_x)
    print(f"--- {name} ---")
    print("Accuracy:", round(accuracy_score(test_y, preds)*100,2), "%")
    print(classification_report(test_y, preds))

import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load Iris dataset
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.Series(iris.target, name='Species')

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42,
                                                    stratify=y)  # maintain class proportion

# Optional: feature scaling for some models
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier

# Initialize models
models = {
    'Logistic Regression': LogisticRegression(max_iter=200),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'K-Nearest Neighbors': KNeighborsClassifier(n_neighbors=5),
    'Support Vector Machine': SVC(kernel='linear', probability=True, random_state=42),
    'AdaBoost': AdaBoostClassifier(n_estimators=50, random_state=42)
}

# Dictionary to store accuracy
accuracy_dict = {}

for name, model in models.items():
    # Logistic Regression and SVM benefit from scaling
    if name in ['Logistic Regression', 'Support Vector Machine']:
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    accuracy_dict[name] = acc
    print(f"\n{name} Accuracy: {acc:.4f}")
    print(classification_report(y_test, y_pred, target_names=iris.target_names))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Optional: Accuracy comparison DataFrame
acc_df = pd.DataFrame(list(accuracy_dict.items()), columns=['Model', 'Accuracy']).sort_values(by='Accuracy', ascending=False)
print("\nModel Accuracy Comparison:\n", acc_df)

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set(style="whitegrid")

# Convert TotalCharges to numeric and handle missing values
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'].fillna(df['TotalCharges'].mean(), inplace=True)

# 1. Basic EDA
print(df.info())
print(df.describe(include="all"))
print(df['Churn'].value_counts(normalize=True) * 100)

# 2. Histogram for numeric variables

numeric_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
df[numeric_cols].hist(figsize=(12,6), bins=30, edgecolor='black')
plt.suptitle("Histograms of Numeric Variables")
plt.show()

# 3. Bar plot for categorical variables
categorical_cols = ['gender', 'SeniorCitizen', 'Partner', 'Dependents',
                    'PhoneService', 'MultipleLines', 'InternetService',
                    'Contract', 'PaperlessBilling', 'PaymentMethod']

for col in categorical_cols:
    plt.figure(figsize=(6,4))
    sns.countplot(x=col, data=df, hue="Churn")
    plt.title(f"{col} vs Churn")
    plt.xticks(rotation=45)
    plt.show()

# 4. Stacked bar chart (Bivariate analysis: IV vs Churn)
for col in categorical_cols:
    cross_tab = pd.crosstab(df[col], df['Churn'], normalize='index') * 100
    cross_tab.plot(kind='bar', stacked=True, figsize=(7,4), colormap="coolwarm")
    plt.title(f"Stacked Bar Chart of {col} vs Churn (%)")
    plt.ylabel("Percentage")
    plt.show()

# 5. Correlation heatmap for numeric variables
plt.figure(figsize=(8,6))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap="Blues", fmt=".2f")
plt.title("Correlation Heatmap of Numeric Variables")
plt.show()



















